services:
  postgres:
    container_name: postgres-sql-itsm
    image: ankane/pgvector:latest         # ← change ici
    environment:
      POSTGRES_USER: itsm
      POSTGRES_PASSWORD: itsm
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: itsm_thales
    volumes:
      - postgres:/var/lib/postgresql/data # ← fix chemin ici
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
