CREATE ROLE debezium WITH REPLICATION LOGIN PASSWORD 'dbzpassword';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO debezium;

CREATE PUBLICATION dbz_publication FOR ALL TABLES;
