spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itsm_thales
    username: itsm
    password: itsm
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
    cache:
      type: redis
      redis:
        time-to-live: 600000 # 10 minutes
        cache-null-values: false
        use-key-prefix: true
        key-prefix: "itsm:"
  batch:
    jdbc:
      initialize-schema: always
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 60s



  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ticket-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: itsm
    password: itsm
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li1shCn5pGbU7yzr
            client-secret: f2f7b2d2a2b8da79add83f57c585c5fc7e53b2cc
            scope: read:user
            redirect-uri: "http://localhost:4200/login/oauth2/code/github"
            client-name: GitHub
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

application:
  security:
    jwt:
      secret-key: asdasd5464zkkekfkrjrnrjkejejkjzeJNJD5885DEJJJEJJRFJakkak
      expiration: 8640000

  mailing:
    frontend:
      activation_url: http://localhost:4200/activation-account

  file:
    upload:
      media-output-path: ./uploads

cloudinary:
  cloud_name: dgvxs4oqz
  api_key: 259165191987951
  api_secret: ivYu59WIVFGDmigV8UwQePvCwPY

ollama:
  url: http://localhost:11434
  model: llama3.1

servicenow:
  url: https://dev193381.service-now.com/api/now/table/incident
  username: aes.creator
  password: Oyz/49JcS!vA

server:
  port: 8090
